### ISSUE TITLE
When first opening the page, styles take a moment to load

### ISSUE THREAD

**Issue by jportella93** [jportella93/make-me-drink-client#14]
It's probably related to how gatsby handles styled-components, should be an easy fix.

To reproduce: 
1. Open https://makemedrink.netlify.app/
2. this is shown for a second
![Screenshot 2020-10-08 at 14 24 43](https://user-images.githubusercontent.com/35599326/95458092-07665200-0972-11eb-8b41-0b7660c8d65a.png)

3. It then updates to its definitve state
![Screenshot 2020-10-08 at 14 24 45](https://user-images.githubusercontent.com/35599326/95458201-24028a00-0972-11eb-8b59-5ba726a12511.png)

**Comment by ahmad-reza619** [comment]
hey, @jportella93 , after a bit of researching, i understand that this is because styled component in gatsby load only when it render the page, and maybe we should probably use [this plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-styled-components) to enforce gatsby to compile the css at build, rather than when the page render

**Comment by jportella93** [comment]
That seems like an easy fix, feel free to tackle it :)
